<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
 "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Generated by graphviz version 2.40.1 (20161225.0304)
 -->
<!-- Title: %3 Pages: 1 -->
<svg width="4152pt" height="116pt"
 viewBox="0.00 0.00 4151.60 116.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 112)">
<title>%3</title>
<polygon fill="#ffffff" stroke="transparent" points="-4,4 -4,-112 4147.5965,-112 4147.5965,4 -4,4"/>
<!-- Antonio Mendes -->
<g id="node1" class="node">
<title>Antonio Mendes</title>
<g id="a_node1"><a xlink:href="Antonio Mendes.html" xlink:title="Antonio Mendes">
<ellipse fill="#f0f8ff" stroke="#000000" cx="204.9834" cy="-90" rx="69.1078" ry="18"/>
<text text-anchor="middle" x="204.9834" y="-85.8" font-family="Times,serif" font-size="14.00" fill="#000000">Antonio Mendes</text>
</a>
</g>
</g>
<!-- Ponte de S. Joao -->
<g id="node2" class="node">
<title>Ponte de S. Joao</title>
<ellipse fill="none" stroke="#000000" cx="204.9834" cy="-18" rx="68.6392" ry="18"/>
<text text-anchor="middle" x="204.9834" y="-13.8" font-family="Times,serif" font-size="14.00" fill="#000000">Ponte de S. Joao</text>
</g>
<!-- Antonio Mendes&#45;&#45;Ponte de S. Joao -->
<g id="edge1" class="edge">
<title>Antonio Mendes&#45;&#45;Ponte de S. Joao</title>
<path fill="none" stroke="#000000" d="M204.9834,-71.8314C204.9834,-61 204.9834,-47.2876 204.9834,-36.4133"/>
</g>
<!-- Musical da D. Josefa -->
<g id="node3" class="node">
<title>Musical da D. Josefa</title>
<ellipse fill="none" stroke="#000000" cx="375.9834" cy="-18" rx="84.0496" ry="18"/>
<text text-anchor="middle" x="375.9834" y="-13.8" font-family="Times,serif" font-size="14.00" fill="#000000">Musical da D. Josefa</text>
</g>
<!-- Antonio Mendes&#45;&#45;Musical da D. Josefa -->
<g id="edge2" class="edge">
<title>Antonio Mendes&#45;&#45;Musical da D. Josefa</title>
<path fill="none" stroke="#000000" d="M241.6672,-74.5542C269.9302,-62.654 308.8958,-46.2474 337.581,-34.1694"/>
</g>
<!-- Opera S. Luis -->
<g id="node4" class="node">
<title>Opera S. Luis</title>
<ellipse fill="none" stroke="#000000" cx="58.9834" cy="-18" rx="58.9668" ry="18"/>
<text text-anchor="middle" x="58.9834" y="-13.8" font-family="Times,serif" font-size="14.00" fill="#000000">Opera S. Luis</text>
</g>
<!-- Antonio Mendes&#45;&#45;Opera S. Luis -->
<g id="edge3" class="edge">
<title>Antonio Mendes&#45;&#45;Opera S. Luis</title>
<path fill="none" stroke="#000000" d="M172.5812,-74.0209C148.0505,-61.9235 114.5517,-45.4036 90.2928,-33.4403"/>
</g>
<!-- Jose Castro -->
<g id="node5" class="node">
<title>Jose Castro</title>
<g id="a_node5"><a xlink:href="Jose Castro.html" xlink:title="Jose Castro">
<ellipse fill="#f0f8ff" stroke="#000000" cx="728.9834" cy="-90" rx="50.7734" ry="18"/>
<text text-anchor="middle" x="728.9834" y="-85.8" font-family="Times,serif" font-size="14.00" fill="#000000">Jose Castro</text>
</a>
</g>
</g>
<!-- Jose Castro&#45;&#45;Ponte de S. Joao -->
<g id="edge7" class="edge">
<title>Jose Castro&#45;&#45;Ponte de S. Joao</title>
<path fill="none" stroke="#000000" d="M679.564,-85.7479C597.0261,-78.2595 426.0664,-61.0983 282.9834,-36 273.9489,-34.4153 264.3884,-32.4512 255.1736,-30.4088"/>
</g>
<!-- Jose Castro&#45;&#45;Musical da D. Josefa -->
<g id="edge9" class="edge">
<title>Jose Castro&#45;&#45;Musical da D. Josefa</title>
<path fill="none" stroke="#000000" d="M684.9894,-81.0267C622.5202,-68.2851 507.8631,-44.899 437.1469,-30.4753"/>
</g>
<!-- A vida do cais -->
<g id="node6" class="node">
<title>A vida do cais</title>
<g id="a_node6"><a xlink:href="A vida do cais.html" xlink:title="A vida do cais">
<ellipse fill="#7cfc00" stroke="#000000" cx="1017.9834" cy="-18" rx="60.4204" ry="18"/>
<text text-anchor="middle" x="1017.9834" y="-13.8" font-family="Times,serif" font-size="14.00" fill="#000000">A vida do cais</text>
</a>
</g>
</g>
<!-- Jose Castro&#45;&#45;A vida do cais -->
<g id="edge4" class="edge">
<title>Jose Castro&#45;&#45;A vida do cais</title>
<path fill="none" stroke="#000000" d="M771.204,-79.829C815.5265,-69.1065 887.22,-51.6353 948.9834,-36 956.5443,-34.086 964.5626,-32.0239 972.3553,-30.0025"/>
</g>
<!-- Portugal Renascentista -->
<g id="node7" class="node">
<title>Portugal Renascentista</title>
<g id="a_node7"><a xlink:href="Portugal Renascentista.html" xlink:title="Portugal Renascentista">
<ellipse fill="#7cfc00" stroke="#000000" cx="848.9834" cy="-18" rx="90.8143" ry="18"/>
<text text-anchor="middle" x="848.9834" y="-13.8" font-family="Times,serif" font-size="14.00" fill="#000000">Portugal Renascentista</text>
</a>
</g>
</g>
<!-- Jose Castro&#45;&#45;Portugal Renascentista -->
<g id="edge5" class="edge">
<title>Jose Castro&#45;&#45;Portugal Renascentista</title>
<path fill="none" stroke="#000000" d="M755.0216,-74.3771C774.3224,-62.7966 800.6143,-47.0214 820.4785,-35.1029"/>
</g>
<!-- O Papagaio de S. Jorge do Campo -->
<g id="node8" class="node">
<title>O Papagaio de S. Jorge do Campo</title>
<g id="a_node8"><a xlink:href="O Papagaio de S. Jorge do Campo.html" xlink:title="O Papagaio de S. Jorge do Campo">
<ellipse fill="#7cfc00" stroke="#000000" cx="608.9834" cy="-18" rx="131.079" ry="18"/>
<text text-anchor="middle" x="608.9834" y="-13.8" font-family="Times,serif" font-size="14.00" fill="#000000">O Papagaio de S. Jorge do Campo</text>
</a>
</g>
</g>
<!-- Jose Castro&#45;&#45;O Papagaio de S. Jorge do Campo -->
<g id="edge6" class="edge">
<title>Jose Castro&#45;&#45;O Papagaio de S. Jorge do Campo</title>
<path fill="none" stroke="#000000" d="M702.9452,-74.3771C683.9201,-62.962 658.1022,-47.4713 638.3435,-35.6161"/>
</g>
<!-- Sarua Museu Sul Americano do Rio de Janeiro -->
<g id="node9" class="node">
<title>Sarua Museu Sul Americano do Rio de Janeiro</title>
<g id="a_node9"><a xlink:href="Sarua Museu Sul Americano do Rio de Janeiro.html" xlink:title="Sarua Museu Sul Americano do Rio de Janeiro">
<ellipse fill="#ffd700" stroke="#000000" cx="1271.9834" cy="-18" rx="175.7919" ry="18"/>
<text text-anchor="middle" x="1271.9834" y="-13.8" font-family="Times,serif" font-size="14.00" fill="#000000">Sarua Museu Sul Americano do Rio de Janeiro</text>
</a>
</g>
</g>
<!-- Jose Castro&#45;&#45;Sarua Museu Sul Americano do Rio de Janeiro -->
<g id="edge8" class="edge">
<title>Jose Castro&#45;&#45;Sarua Museu Sul Americano do Rio de Janeiro</title>
<path fill="none" stroke="#000000" d="M776.6951,-83.6736C862.8732,-72.2467 1046.4633,-47.9032 1164.2997,-32.2785"/>
</g>
<!-- Ana Josefa Tralhao -->
<g id="node10" class="node">
<title>Ana Josefa Tralhao</title>
<g id="a_node10"><a xlink:href="Ana Josefa Tralhao.html" xlink:title="Ana Josefa Tralhao">
<ellipse fill="#f0f8ff" stroke="#000000" cx="1402.9834" cy="-90" rx="78.2952" ry="18"/>
<text text-anchor="middle" x="1402.9834" y="-85.8" font-family="Times,serif" font-size="14.00" fill="#000000">Ana Josefa Tralhao</text>
</a>
</g>
</g>
<!-- Ana Josefa Tralhao&#45;&#45;A vida do cais -->
<g id="edge11" class="edge">
<title>Ana Josefa Tralhao&#45;&#45;A vida do cais</title>
<path fill="none" stroke="#000000" d="M1336.6962,-80.3689C1272.5365,-70.6478 1172.6757,-54.4634 1086.9834,-36 1079.1169,-34.3051 1070.7967,-32.3104 1062.7605,-30.2775"/>
</g>
<!-- Ana Josefa Tralhao&#45;&#45;Sarua Museu Sul Americano do Rio de Janeiro -->
<g id="edge13" class="edge">
<title>Ana Josefa Tralhao&#45;&#45;Sarua Museu Sul Americano do Rio de Janeiro</title>
<path fill="none" stroke="#000000" d="M1372.6001,-73.3008C1352.1925,-62.0844 1325.3279,-47.3191 1304.4916,-35.8671"/>
</g>
<!-- Pensao do Guarau -->
<g id="node11" class="node">
<title>Pensao do Guarau</title>
<ellipse fill="none" stroke="#000000" cx="1695.9834" cy="-18" rx="74.4016" ry="18"/>
<text text-anchor="middle" x="1695.9834" y="-13.8" font-family="Times,serif" font-size="14.00" fill="#000000">Pensao do Guarau</text>
</g>
<!-- Ana Josefa Tralhao&#45;&#45;Pensao do Guarau -->
<g id="edge10" class="edge">
<title>Ana Josefa Tralhao&#45;&#45;Pensao do Guarau</title>
<path fill="none" stroke="#000000" d="M1456.7241,-76.7941C1509.9211,-63.7218 1590.8388,-43.8376 1643.5692,-30.8799"/>
</g>
<!-- O Festa do Povo -->
<g id="node12" class="node">
<title>O Festa do Povo</title>
<g id="a_node12"><a xlink:href="O Festa do Povo.html" xlink:title="O Festa do Povo">
<ellipse fill="#ffd700" stroke="#000000" cx="1534.9834" cy="-18" rx="68.6405" ry="18"/>
<text text-anchor="middle" x="1534.9834" y="-13.8" font-family="Times,serif" font-size="14.00" fill="#000000">O Festa do Povo</text>
</a>
</g>
</g>
<!-- Ana Josefa Tralhao&#45;&#45;O Festa do Povo -->
<g id="edge12" class="edge">
<title>Ana Josefa Tralhao&#45;&#45;O Festa do Povo</title>
<path fill="none" stroke="#000000" d="M1433.5986,-73.3008C1455.0759,-61.5859 1483.6507,-45.9997 1504.9893,-34.3604"/>
</g>
<!-- Felix Antunes -->
<g id="node13" class="node">
<title>Felix Antunes</title>
<g id="a_node13"><a xlink:href="Felix Antunes.html" xlink:title="Felix Antunes">
<ellipse fill="#f0f8ff" stroke="#000000" cx="1695.9834" cy="-90" rx="59.4772" ry="18"/>
<text text-anchor="middle" x="1695.9834" y="-85.8" font-family="Times,serif" font-size="14.00" fill="#000000">Felix Antunes</text>
</a>
</g>
</g>
<!-- Felix Antunes&#45;&#45;Pensao do Guarau -->
<g id="edge14" class="edge">
<title>Felix Antunes&#45;&#45;Pensao do Guarau</title>
<path fill="none" stroke="#000000" d="M1695.9834,-71.8314C1695.9834,-61 1695.9834,-47.2876 1695.9834,-36.4133"/>
</g>
<!-- Felix Antunes&#45;&#45;O Festa do Povo -->
<g id="edge16" class="edge">
<title>Felix Antunes&#45;&#45;O Festa do Povo</title>
<path fill="none" stroke="#000000" d="M1662.6241,-75.0816C1635.5451,-62.9717 1597.4781,-45.9479 1569.9707,-33.6465"/>
</g>
<!-- Igreja Nova Brasil -->
<g id="node14" class="node">
<title>Igreja Nova Brasil</title>
<ellipse fill="none" stroke="#000000" cx="1863.9834" cy="-18" rx="75.3535" ry="18"/>
<text text-anchor="middle" x="1863.9834" y="-13.8" font-family="Times,serif" font-size="14.00" fill="#000000">Igreja Nova Brasil</text>
</g>
<!-- Felix Antunes&#45;&#45;Igreja Nova Brasil -->
<g id="edge15" class="edge">
<title>Felix Antunes&#45;&#45;Igreja Nova Brasil</title>
<path fill="none" stroke="#000000" d="M1730.3861,-75.256C1758.5133,-63.2015 1798.1995,-46.1931 1827.0038,-33.8484"/>
</g>
<!-- Joao Arantes -->
<g id="node15" class="node">
<title>Joao Arantes</title>
<g id="a_node15"><a xlink:href="Joao Arantes.html" xlink:title="Joao Arantes">
<ellipse fill="#f0f8ff" stroke="#000000" cx="1894.9834" cy="-90" rx="55.5924" ry="18"/>
<text text-anchor="middle" x="1894.9834" y="-85.8" font-family="Times,serif" font-size="14.00" fill="#000000">Joao Arantes</text>
</a>
</g>
</g>
<!-- Joao Arantes&#45;&#45;Pensao do Guarau -->
<g id="edge18" class="edge">
<title>Joao Arantes&#45;&#45;Pensao do Guarau</title>
<path fill="none" stroke="#000000" d="M1857.553,-76.4574C1823.326,-64.0737 1772.784,-45.7872 1737.3674,-32.9731"/>
</g>
<!-- Joao Arantes&#45;&#45;Igreja Nova Brasil -->
<g id="edge20" class="edge">
<title>Joao Arantes&#45;&#45;Igreja Nova Brasil</title>
<path fill="none" stroke="#000000" d="M1887.1608,-71.8314C1882.4255,-60.8334 1876.4114,-46.865 1871.6961,-35.9134"/>
</g>
<!-- Festa do Povo -->
<g id="node16" class="node">
<title>Festa do Povo</title>
<g id="a_node16"><a xlink:href="Festa do Povo.html" xlink:title="Festa do Povo">
<ellipse fill="#ffd700" stroke="#000000" cx="2246.9834" cy="-18" rx="60.4462" ry="18"/>
<text text-anchor="middle" x="2246.9834" y="-13.8" font-family="Times,serif" font-size="14.00" fill="#000000">Festa do Povo</text>
</a>
</g>
</g>
<!-- Joao Arantes&#45;&#45;Festa do Povo -->
<g id="edge17" class="edge">
<title>Joao Arantes&#45;&#45;Festa do Povo</title>
<path fill="none" stroke="#000000" d="M1943.1361,-80.9495C2017.606,-66.9267 2154.5171,-41.0344 2176.9834,-36 2185.0647,-34.1891 2193.6318,-32.1155 2201.8971,-30.0351"/>
</g>
<!-- Igreja Jesuita de Sao Paulo -->
<g id="node17" class="node">
<title>Igreja Jesuita de Sao Paulo</title>
<ellipse fill="none" stroke="#000000" cx="2062.9834" cy="-18" rx="105.2887" ry="18"/>
<text text-anchor="middle" x="2062.9834" y="-13.8" font-family="Times,serif" font-size="14.00" fill="#000000">Igreja Jesuita de Sao Paulo</text>
</g>
<!-- Joao Arantes&#45;&#45;Igreja Jesuita de Sao Paulo -->
<g id="edge19" class="edge">
<title>Joao Arantes&#45;&#45;Igreja Jesuita de Sao Paulo</title>
<path fill="none" stroke="#000000" d="M1928.5769,-75.6028C1956.0587,-63.8249 1994.963,-47.1516 2023.8491,-34.7718"/>
</g>
<!-- Manuel Soares -->
<g id="node18" class="node">
<title>Manuel Soares</title>
<g id="a_node18"><a xlink:href="Manuel Soares.html" xlink:title="Manuel Soares">
<ellipse fill="#f0f8ff" stroke="#000000" cx="2062.9834" cy="-90" rx="62.8172" ry="18"/>
<text text-anchor="middle" x="2062.9834" y="-85.8" font-family="Times,serif" font-size="14.00" fill="#000000">Manuel Soares</text>
</a>
</g>
</g>
<!-- Manuel Soares&#45;&#45;Festa do Povo -->
<g id="edge21" class="edge">
<title>Manuel Soares&#45;&#45;Festa do Povo</title>
<path fill="none" stroke="#000000" d="M2100.2185,-75.4297C2132.2467,-62.897 2178.1976,-44.9162 2210.118,-32.4256"/>
</g>
<!-- Manuel Soares&#45;&#45;Igreja Jesuita de Sao Paulo -->
<g id="edge22" class="edge">
<title>Manuel Soares&#45;&#45;Igreja Jesuita de Sao Paulo</title>
<path fill="none" stroke="#000000" d="M2062.9834,-71.8314C2062.9834,-61 2062.9834,-47.2876 2062.9834,-36.4133"/>
</g>
<!-- Jose Florencio Soares Castro -->
<g id="node19" class="node">
<title>Jose Florencio Soares Castro</title>
<g id="a_node19"><a xlink:href="Jose Florencio Soares Castro.html" xlink:title="Jose Florencio Soares Castro">
<ellipse fill="#f0f8ff" stroke="#000000" cx="2255.9834" cy="-90" rx="112.5556" ry="18"/>
<text text-anchor="middle" x="2255.9834" y="-85.8" font-family="Times,serif" font-size="14.00" fill="#000000">Jose Florencio Soares Castro</text>
</a>
</g>
</g>
<!-- Jose Florencio Soares Castro&#45;&#45;Festa do Povo -->
<g id="edge23" class="edge">
<title>Jose Florencio Soares Castro&#45;&#45;Festa do Povo</title>
<path fill="none" stroke="#000000" d="M2253.7123,-71.8314C2252.3584,-61 2250.6443,-47.2876 2249.285,-36.4133"/>
</g>
<!-- Jose Florencio Soares Castro&#45;&#45;Igreja Jesuita de Sao Paulo -->
<g id="edge25" class="edge">
<title>Jose Florencio Soares Castro&#45;&#45;Igreja Jesuita de Sao Paulo</title>
<path fill="none" stroke="#000000" d="M2211.2202,-73.3008C2179.9292,-61.6275 2138.3342,-46.1102 2107.1707,-34.4844"/>
</g>
<!-- Comandante militar da zona territorial centro -->
<g id="node20" class="node">
<title>Comandante militar da zona territorial centro</title>
<ellipse fill="none" stroke="#000000" cx="2494.9834" cy="-18" rx="169.9257" ry="18"/>
<text text-anchor="middle" x="2494.9834" y="-13.8" font-family="Times,serif" font-size="14.00" fill="#000000">Comandante militar da zona territorial centro</text>
</g>
<!-- Jose Florencio Soares Castro&#45;&#45;Comandante militar da zona territorial centro -->
<g id="edge24" class="edge">
<title>Jose Florencio Soares Castro&#45;&#45;Comandante militar da zona territorial centro</title>
<path fill="none" stroke="#000000" d="M2309.0252,-74.0209C2347.3939,-62.4621 2399.1651,-46.8658 2438.339,-35.0644"/>
</g>
<!-- Joao Ferreira -->
<g id="node21" class="node">
<title>Joao Ferreira</title>
<g id="a_node21"><a xlink:href="Joao Ferreira.html" xlink:title="Joao Ferreira">
<ellipse fill="#f0f8ff" stroke="#000000" cx="3066.9834" cy="-90" rx="56.5269" ry="18"/>
<text text-anchor="middle" x="3066.9834" y="-85.8" font-family="Times,serif" font-size="14.00" fill="#000000">Joao Ferreira</text>
</a>
</g>
</g>
<!-- Joao Ferreira&#45;&#45;Festa do Povo -->
<g id="edge27" class="edge">
<title>Joao Ferreira&#45;&#45;Festa do Povo</title>
<path fill="none" stroke="#000000" d="M3011.0117,-87.31C2860.5768,-79.867 2449.8762,-58.0861 2315.9834,-36 2307.555,-34.6097 2298.6574,-32.6612 2290.1558,-30.5565"/>
</g>
<!-- Joao Ferreira&#45;&#45;Comandante militar da zona territorial centro -->
<g id="edge33" class="edge">
<title>Joao Ferreira&#45;&#45;Comandante militar da zona territorial centro</title>
<path fill="none" stroke="#000000" d="M3014.1963,-83.3555C2921.4072,-71.6757 2727.2813,-47.2403 2604.4672,-31.7812"/>
</g>
<!-- Turtulia com as Marias -->
<g id="node22" class="node">
<title>Turtulia com as Marias</title>
<ellipse fill="none" stroke="#000000" cx="3729.9834" cy="-18" rx="92.1374" ry="18"/>
<text text-anchor="middle" x="3729.9834" y="-13.8" font-family="Times,serif" font-size="14.00" fill="#000000">Turtulia com as Marias</text>
</g>
<!-- Joao Ferreira&#45;&#45;Turtulia com as Marias -->
<g id="edge26" class="edge">
<title>Joao Ferreira&#45;&#45;Turtulia com as Marias</title>
<path fill="none" stroke="#000000" d="M3122.5946,-86.1498C3223.6904,-78.8186 3444.2265,-61.2978 3628.9834,-36 3640.277,-34.4536 3652.2364,-32.5554 3663.8227,-30.578"/>
</g>
<!-- A bela encantada -->
<g id="node23" class="node">
<title>A bela encantada</title>
<ellipse fill="none" stroke="#000000" cx="3548.9834" cy="-18" rx="70.5168" ry="18"/>
<text text-anchor="middle" x="3548.9834" y="-13.8" font-family="Times,serif" font-size="14.00" fill="#000000">A bela encantada</text>
</g>
<!-- Joao Ferreira&#45;&#45;A bela encantada -->
<g id="edge28" class="edge">
<title>Joao Ferreira&#45;&#45;A bela encantada</title>
<path fill="none" stroke="#000000" d="M3120.8618,-84.2849C3198.2176,-75.7348 3345.0862,-58.2156 3468.9834,-36 3478.0916,-34.3668 3487.732,-32.4026 3497.0472,-30.3807"/>
</g>
<!-- Os 3 da vigairada -->
<g id="node24" class="node">
<title>Os 3 da vigairada</title>
<g id="a_node24"><a xlink:href="Os 3 da vigairada.html" xlink:title="Os 3 da vigairada">
<ellipse fill="#ffd700" stroke="#000000" cx="2985.9834" cy="-18" rx="72.472" ry="18"/>
<text text-anchor="middle" x="2985.9834" y="-13.8" font-family="Times,serif" font-size="14.00" fill="#000000">Os 3 da vigairada</text>
</a>
</g>
</g>
<!-- Joao Ferreira&#45;&#45;Os 3 da vigairada -->
<g id="edge29" class="edge">
<title>Joao Ferreira&#45;&#45;Os 3 da vigairada</title>
<path fill="none" stroke="#000000" d="M3047.7875,-72.937C3035.0626,-61.626 3018.4151,-46.8282 3005.6041,-35.4407"/>
</g>
<!-- O mago e a maga -->
<g id="node25" class="node">
<title>O mago e a maga</title>
<ellipse fill="none" stroke="#000000" cx="3147.9834" cy="-18" rx="71.9704" ry="18"/>
<text text-anchor="middle" x="3147.9834" y="-13.8" font-family="Times,serif" font-size="14.00" fill="#000000">O mago e a maga</text>
</g>
<!-- Joao Ferreira&#45;&#45;O mago e a maga -->
<g id="edge30" class="edge">
<title>Joao Ferreira&#45;&#45;O mago e a maga</title>
<path fill="none" stroke="#000000" d="M3086.1792,-72.937C3098.9042,-61.626 3115.5516,-46.8282 3128.3626,-35.4407"/>
</g>
<!-- A menina perdida do bosque -->
<g id="node26" class="node">
<title>A menina perdida do bosque</title>
<ellipse fill="none" stroke="#000000" cx="3348.9834" cy="-18" rx="111.0947" ry="18"/>
<text text-anchor="middle" x="3348.9834" y="-13.8" font-family="Times,serif" font-size="14.00" fill="#000000">A menina perdida do bosque</text>
</g>
<!-- Joao Ferreira&#45;&#45;A menina perdida do bosque -->
<g id="edge31" class="edge">
<title>Joao Ferreira&#45;&#45;A menina perdida do bosque</title>
<path fill="none" stroke="#000000" d="M3111.3561,-78.6708C3159.3619,-66.414 3236.161,-46.8057 3289.4009,-33.2125"/>
</g>
<!-- O crime da fereira Amanda -->
<g id="node27" class="node">
<title>O crime da fereira Amanda</title>
<ellipse fill="none" stroke="#000000" cx="2788.9834" cy="-18" rx="106.2147" ry="18"/>
<text text-anchor="middle" x="2788.9834" y="-13.8" font-family="Times,serif" font-size="14.00" fill="#000000">O crime da fereira Amanda</text>
</g>
<!-- Joao Ferreira&#45;&#45;O crime da fereira Amanda -->
<g id="edge32" class="edge">
<title>Joao Ferreira&#45;&#45;O crime da fereira Amanda</title>
<path fill="none" stroke="#000000" d="M3022.9335,-78.5914C2975.4717,-66.2991 2899.7188,-46.6797 2847.3328,-33.1121"/>
</g>
<!-- Francisco Martins -->
<g id="node28" class="node">
<title>Francisco Martins</title>
<g id="a_node28"><a xlink:href="Francisco Martins.html" xlink:title="Francisco Martins">
<ellipse fill="#f0f8ff" stroke="#000000" cx="3779.9834" cy="-90" rx="74.4186" ry="18"/>
<text text-anchor="middle" x="3779.9834" y="-85.8" font-family="Times,serif" font-size="14.00" fill="#000000">Francisco Martins</text>
</a>
</g>
</g>
<!-- Francisco Martins&#45;&#45;Turtulia com as Marias -->
<g id="edge34" class="edge">
<title>Francisco Martins&#45;&#45;Turtulia com as Marias</title>
<path fill="none" stroke="#000000" d="M3767.6238,-72.2022C3759.9314,-61.1252 3750.0723,-46.928 3742.374,-35.8425"/>
</g>
<!-- Francisco Martins&#45;&#45;A bela encantada -->
<g id="edge37" class="edge">
<title>Francisco Martins&#45;&#45;A bela encantada</title>
<path fill="none" stroke="#000000" d="M3734.3452,-75.7751C3693.5848,-63.0706 3634.2304,-44.5705 3593.7407,-31.9503"/>
</g>
<!-- Capitao -->
<g id="node29" class="node">
<title>Capitao</title>
<ellipse fill="none" stroke="#000000" cx="4105.9834" cy="-18" rx="37.7266" ry="18"/>
<text text-anchor="middle" x="4105.9834" y="-13.8" font-family="Times,serif" font-size="14.00" fill="#000000">Capitao</text>
</g>
<!-- Francisco Martins&#45;&#45;Capitao -->
<g id="edge35" class="edge">
<title>Francisco Martins&#45;&#45;Capitao</title>
<path fill="none" stroke="#000000" d="M3844.1674,-80.8426C3901.2041,-71.9353 3986.5251,-56.7154 4058.9834,-36 4065.0321,-34.2707 4071.3963,-32.0903 4077.4199,-29.8493"/>
</g>
<!-- Espedicao ao Sul do Brasil -->
<g id="node30" class="node">
<title>Espedicao ao Sul do Brasil</title>
<g id="a_node30"><a xlink:href="Espedicao ao Sul do Brasil.html" xlink:title="Espedicao ao Sul do Brasil">
<ellipse fill="#ffd700" stroke="#000000" cx="3944.9834" cy="-18" rx="105.306" ry="18"/>
<text text-anchor="middle" x="3944.9834" y="-13.8" font-family="Times,serif" font-size="14.00" fill="#000000">Espedicao ao Sul do Brasil</text>
</a>
</g>
</g>
<!-- Francisco Martins&#45;&#45;Espedicao ao Sul do Brasil -->
<g id="edge36" class="edge">
<title>Francisco Martins&#45;&#45;Espedicao ao Sul do Brasil</title>
<path fill="none" stroke="#000000" d="M3816.1933,-74.1993C3842.945,-62.5258 3879.2978,-46.6628 3906.5601,-34.7665"/>
</g>
<!-- Joaquina de Sampaio -->
<g id="node31" class="node">
<title>Joaquina de Sampaio</title>
<g id="a_node31"><a xlink:href="Joaquina de Sampaio.html" xlink:title="Joaquina de Sampaio">
<ellipse fill="#f0f8ff" stroke="#000000" cx="4055.9834" cy="-90" rx="85.0187" ry="18"/>
<text text-anchor="middle" x="4055.9834" y="-85.8" font-family="Times,serif" font-size="14.00" fill="#000000">Joaquina de Sampaio</text>
</a>
</g>
</g>
<!-- Joaquina de Sampaio&#45;&#45;Turtulia com as Marias -->
<g id="edge38" class="edge">
<title>Joaquina de Sampaio&#45;&#45;Turtulia com as Marias</title>
<path fill="none" stroke="#000000" d="M3996.9472,-76.9613C3938.6908,-64.0949 3850.0263,-44.5125 3791.0691,-31.4913"/>
</g>
<!-- Joaquina de Sampaio&#45;&#45;Capitao -->
<g id="edge39" class="edge">
<title>Joaquina de Sampaio&#45;&#45;Capitao</title>
<path fill="none" stroke="#000000" d="M4068.6005,-71.8314C4076.3537,-60.6667 4086.2327,-46.441 4093.8877,-35.4177"/>
</g>
</g>
</svg>
