Insert into Unidade_Curricular

(idUnidade_Curricular, Ano, Semestre)

values

('Álgebra Linear EI', 1, 1),
('Cálculo', 1, 1),
('Tópicos de Matemática Discreta', 1, 1),
('Programação Funcional', 1, 1),
('Elementos de Engenharia de Sistemas', 1, 1),
('Laboratórios de Informática I', 1, 1),
('Sistemas de Computação', 1, 2),
('Análise', 1, 2),
('Tópicos de Física Moderna', 1, 2),
('Lógica EI', 1, 2),
('Programação Imperativa', 1, 2),
('Laboratórios de Informática II', 1, 2),
('Introdução aos Sistemas Dinâmicos', 2, 1),
('Estatística Aplicada', 2, 1),
('Engenharia Económica', 2, 1),
('Arquitetura de Computadores', 2, 1),
('Comunicação de Dados', 2, 1),
('Algoritmos e Complexidade', 2, 1),
('Sistemas Operativos', 2, 2),
('Programação Orientada aos Objetos', 2, 2),
('Eletromagnetismo EE', 2, 2),
('Cálculo de Programas', 2, 2),
('Laboratórios de Informática III', 2, 2),
('Bases de Dados', 3, 1),
('Desenvolvimento de Sistemas de Software', 3, 1),
('Modelos Determinísticos de Investigação Operacional', 3, 1),
('Sistemas Distribuídos', 3, 1),
('Redes de Computadores', 3, 1),
('Métodos Numéricos e Otimização não Linear', 3, 1),
('Sistemas de Representação de Conhecimento e Raciocínio', 3, 2),
('Computação Gráfica', 3, 2),
('Modelos Estocásticos de Investigação Operacional', 3, 2),
('Comunicações por Computador', 3, 2),
('Processamento de Linguagens', 3, 2),
('Laboratórios de Informática IV', 3, 2),
('Bio-UC1-Algoritmos para Análise de Sequências Biológicas', 4, 1),
('Bio-UC2-Laboratórios de Bioinformática', 4, 1),
('CG-UC1-Visualização e Iluminação I', 4, 1),
('CG-UC2-Visão por Computador', 4, 1),
('BI-UC1-Sistemas Operacionais', 4, 1),
('BI-UC2-Data Warehousing', 4, 1),
('SDC-UC1-Criptografia e Segurança da Informação', 4, 1), 
('SDC-UC2-Paradigmas de Sistemas Distribuídos', 4, 1),
('EA-UC1-Infraestruturas de Centro de Dados', 4, 1),
('EA-UC2-Administração de Base de Dados', 4, 1),
('ESS-UC1-Engenharia de Requisitos'	, 4, 1),
('ESS-UC2-Arquiteturas de Software', 4, 1),
('CPD-UC1-Arquiteturas Avançadas', 4, 1),
('CPD-UC2-Paradigmas de Computação Paralela', 4, 1),
('ERS-UC1-Tecnologias e Protocolos de Rede', 4, 1),
('ERS-UC2-Gestão de Redes', 4, 1),
('SI-UC1-Agentes Inteligentes', 4, 1),
('SI-UC2-Aprendizaem e Extração de Conhecimento', 4, 1),
('MFES-UC1-Especificação e Modelação', 4, 1),
('MFES-UC2-Análise e Teste de Software', 4, 1),
('PLC-UC1-Gramáticas na Compreensão de Software', 4, 1),
('PLC-UC2-Processamento e Representação de Informação', 4, 1),
('Mineração de Dados', 4, 1),
('Gestão de Redes', 4, 1),
('Análise e Teste de Software', 4, 1),
('Visão por Computador', 4, 1),
('Computação Paralela', 4, 1),
('Segurança de Sistemas Informáticos', 4, 1),
('Processamento de Dados com Streams de Java', 4, 1),
('Administração e Exploração de Bases de Dados', 4, 1),
('Engenharia de Requisitos', 4, 1),
('Scripting no Processamento de Linguagem Natural', 4, 1),
('System Deployment and Benchmarking', 4, 1),
('Inteligência Ambiente - Tecnologias e Aplicações', 4, 1),	
('BI-UC3-Processamento Analítico de Dados', 4, 2),
('BI-UC4-Análise de Dados', 4, 2),
('SDC-UC3-Segurança de Sistemas Informáticos', 4, 2),
('SDC-UC4-Sistemas Distribuídos Confiáveis', 4, 2),
('EA-UC3-Arquiteturas Aplicacionais', 4, 2),
('EA-UC4-Sistemas Interativos', 4, 2),
('ESS-UC3-Gestão do Processo de Software', 4, 2),
('ESS-UC4-Engenharia Web', 4, 2),
('CPD-UC3-Algoritmos Paralelos', 4, 2),
('CPD-UC4-Engenharia dos Sistemas de Computação', 4, 2),
('CG-UC3-Visualização e Iluminação II', 4, 2),
('CG-UC4-Tecnologias e Aplicações', 4, 2),
('ERS-UC3-Redes Multi Serviços', 4, 2),
('ERS-UC4-Serviços e Sistemas Multimédia', 4, 2),
('Bio-UC3-Algoritmos Avançados de Bioinformática', 4, 2),
('Bio-UC4-Extração de Conhecimento de Bases de Dados Biológicas', 4, 2),
('SI-UC3-Computação Natural', 4, 2),
('SI-UC4-Sistemas Autónomos', 4, 2),
('MFES-UC3-Arquitetura e Cálculo', 4, 2),
('MFES-UC4-Verificaçao Formal', 4, 2),
('PLC-UC3-Scripting no Processamento de Linguagem Natural', 4, 2),
('PLC-UC4-Processamento e Representação de Conhecimento', 4, 2);	